/* ================= 冒險模式：戰鬥資料 ================= */
// 傷害分級精神參考自 Boggle 式戰鬥拼字遊戲的通用設計（稀有字母＝雙面刃：磚不好湊但打起來痛），
// 數值全部用專案既有的 LETTER_SCORE／LETTER_POOL 重新映射，非抄襲任何特定作品的表格。
const ADV_SKILLS = {
  lock: { icon: 'L', name: '鎖定磚', desc: '隨機封住 1 格，無法選取；3 次有效攻擊後解除。' },
  curse: { icon: 'C', name: '詛咒磚', desc: '拼入後本次攻擊傷害降低；3 次有效攻擊後解除。' },
  counter: { icon: 'ATK', name: '反擊', desc: '未擊倒時回合結尾扣玩家 HP。' },
  pressure: { icon: '2x', name: '雙重干擾', desc: '有機會一次製造 2 顆負面磚。' },
  boss: { icon: 'BOSS', name: '重擊', desc: 'Boss 反擊較痛，血量要顧。' },
};
function advSkills(...ids) {
  return ids.map(id => ADV_SKILLS[id]);
}
const ADVENTURE_CHAPTERS = [
  {
    id: 'dusty-library',
    title: '塵封的書庫',
    stageTheme: 'dusty-library',
    levels: [
      {
        id: 'paper-mouse',
        name: '紙頁鼠',
        hp: 40,
        atk: 4,
        kind: 'critter',
        skills: advSkills('lock', 'counter'),
      },
      {
        id: 'bookmark-thief',
        name: '書籤小賊',
        hp: 48,
        atk: 4,
        kind: 'critter',
        skills: advSkills('lock', 'counter'),
      },
      {
        id: 'ink-blob',
        name: '墨漬怪',
        hp: 58,
        atk: 5,
        kind: 'blob',
        skills: advSkills('curse', 'counter'),
      },
      {
        id: 'spine-guard',
        name: '書脊守衛',
        hp: 72,
        atk: 5,
        kind: 'book',
        skills: advSkills('lock', 'curse'),
      },
      {
        id: 'bookworm-king',
        name: '蛀書蟲王',
        hp: 95,
        atk: 7,
        kind: 'book',
        boss: true,
        skills: advSkills('lock', 'curse', 'boss'),
      },
    ],
  },
  {
    id: 'ink-gallery',
    title: '墨痕迴廊',
    levels: [
      {
        id: 'dust-scribe',
        name: '灰塵抄寫員',
        hp: 70,
        atk: 6,
        kind: 'critter',
        skills: advSkills('lock', 'curse'),
      },
      {
        id: 'violet-ink',
        name: '紫墨術士',
        hp: 85,
        atk: 7,
        kind: 'blob',
        skills: advSkills('curse', 'counter'),
      },
      {
        id: 'echo-proofreader',
        name: '迴聲校對者',
        hp: 92,
        atk: 7,
        kind: 'critter',
        skills: advSkills('lock', 'counter'),
      },
      {
        id: 'missing-word-ghost',
        name: '漏字幽靈',
        hp: 104,
        atk: 8,
        kind: 'blob',
        skills: advSkills('curse', 'pressure'),
      },
      {
        id: 'archive-book',
        name: '索引巨冊',
        hp: 120,
        atk: 9,
        kind: 'book',
        boss: true,
        skills: advSkills('lock', 'curse', 'boss'),
      },
    ],
  },
  {
    id: 'crooked-fairytale',
    title: '失序童話架',
    levels: [
      {
        id: 'cookie-soldier',
        name: '餅乾士兵',
        hp: 88,
        atk: 7,
        kind: 'critter',
        skills: advSkills('lock', 'counter'),
      },
      {
        id: 'nightcap-cat',
        name: '睡帽貓',
        hp: 96,
        atk: 8,
        kind: 'critter',
        skills: advSkills('curse', 'counter'),
      },
      {
        id: 'glass-slipper-shadow',
        name: '玻璃鞋影子',
        hp: 108,
        atk: 8,
        kind: 'blob',
        skills: advSkills('curse', 'pressure'),
      },
      {
        id: 'paper-crown-queen',
        name: '紙皇冠女王',
        hp: 118,
        atk: 9,
        kind: 'book',
        skills: advSkills('lock', 'curse'),
      },
      {
        id: 'comma-giant',
        name: '逗號巨人',
        hp: 136,
        atk: 10,
        kind: 'book',
        boss: true,
        skills: advSkills('lock', 'pressure', 'boss'),
      },
    ],
  },
  {
    id: 'star-chart-room',
    title: '星圖閱覽室',
    levels: [
      {
        id: 'stardust-moth',
        name: '星塵蛾',
        hp: 102,
        atk: 8,
        kind: 'critter',
        skills: advSkills('curse', 'counter'),
      },
      {
        id: 'moonphase-clerk',
        name: '月相書吏',
        hp: 112,
        atk: 9,
        kind: 'book',
        skills: advSkills('lock', 'counter'),
      },
      {
        id: 'lost-comet',
        name: '迷路彗星',
        hp: 124,
        atk: 9,
        kind: 'blob',
        skills: advSkills('curse', 'pressure'),
      },
      {
        id: 'observatory-golem',
        name: '觀測塔魔像',
        hp: 138,
        atk: 10,
        kind: 'book',
        skills: advSkills('lock', 'pressure'),
      },
      {
        id: 'atlas-curator',
        name: '星圖館長',
        hp: 154,
        atk: 11,
        kind: 'book',
        boss: true,
        skills: advSkills('lock', 'curse', 'boss'),
      },
    ],
  },
  {
    id: 'forbidden-greenhouse',
    title: '禁書溫室',
    levels: [
      {
        id: 'root-vine',
        name: '書根藤',
        hp: 118,
        atk: 9,
        kind: 'critter',
        skills: advSkills('lock', 'counter'),
      },
      {
        id: 'pollen-note',
        name: '花粉筆記',
        hp: 128,
        atk: 10,
        kind: 'blob',
        skills: advSkills('curse', 'counter'),
      },
      {
        id: 'dew-slime',
        name: '露水黏怪',
        hp: 140,
        atk: 10,
        kind: 'blob',
        skills: advSkills('curse', 'pressure'),
      },
      {
        id: 'greenhouse-warden',
        name: '溫室守衛',
        hp: 152,
        atk: 11,
        kind: 'book',
        skills: advSkills('lock', 'pressure'),
      },
      {
        id: 'thousand-page-mandrake',
        name: '千頁曼陀羅',
        hp: 180,
        atk: 12,
        kind: 'book',
        boss: true,
        skills: advSkills('curse', 'pressure', 'boss'),
      },
    ],
  },
  {
    id: 'storm-index-harbor',
    title: '暴風索引港',
    levels: [
      {
        id: 'salt-bookmark',
        name: '海鹽書籤',
        hp: 144,
        atk: 10,
        kind: 'critter',
        skills: advSkills('lock', 'counter'),
      },
      {
        id: 'ragged-sail-letterer',
        name: '破帆字母匠',
        hp: 156,
        atk: 11,
        kind: 'book',
        skills: advSkills('curse', 'counter'),
      },
      {
        id: 'lighthouse-copyeditor',
        name: '燈塔校稿員',
        hp: 170,
        atk: 11,
        kind: 'critter',
        skills: advSkills('lock', 'pressure'),
      },
      {
        id: 'chapter-kraken',
        name: '章節海怪',
        hp: 184,
        atk: 12,
        kind: 'blob',
        skills: advSkills('curse', 'pressure'),
      },
      {
        id: 'storm-binder',
        name: '暴風裝訂師',
        hp: 212,
        atk: 13,
        kind: 'book',
        boss: true,
        skills: advSkills('lock', 'pressure', 'boss'),
      },
    ],
  },
  {
    id: 'living-type-core',
    title: '活字核心',
    levels: [
      {
        id: 'lead-type-ant',
        name: '鉛字工蟻',
        hp: 166,
        atk: 11,
        kind: 'critter',
        skills: advSkills('lock', 'counter'),
      },
      {
        id: 'reverse-print-shade',
        name: '反白幽影',
        hp: 180,
        atk: 12,
        kind: 'blob',
        skills: advSkills('curse', 'pressure'),
      },
      {
        id: 'proof-press-mechanic',
        name: '校樣機械師',
        hp: 194,
        atk: 12,
        kind: 'book',
        skills: advSkills('lock', 'pressure'),
      },
      {
        id: 'mojibake-oracle',
        name: '亂碼先知',
        hp: 210,
        atk: 13,
        kind: 'blob',
        skills: advSkills('curse', 'pressure'),
      },
      {
        id: 'final-type-golem',
        name: '終章活字巨像',
        hp: 243,
        atk: 15,
        kind: 'book',
        boss: true,
        skills: advSkills('lock', 'curse', 'boss'),
      },
    ],
  },
];
const ADV_STAGE_THEMES = {
  'dusty-library': {
    far: 'assets/stages/dusty-library-far.png',
    mid: 'assets/stages/dusty-library-mid.png',
    ground: 'assets/stages/dusty-library-ground.png',
  },
  'ink-gallery': {
    far: 'assets/stages/ink-gallery-far.png',
    mid: 'assets/stages/ink-gallery-mid.png',
    ground: 'assets/stages/ink-gallery-ground.png',
  },
  'crooked-fairytale': {
    far: 'assets/stages/crooked-fairytale-far.png',
    mid: 'assets/stages/crooked-fairytale-mid.png',
    ground: 'assets/stages/crooked-fairytale-ground.png',
  },
  'star-chart-room': {
    far: 'assets/stages/star-chart-room-far.png',
    mid: 'assets/stages/star-chart-room-mid.png',
    ground: 'assets/stages/star-chart-room-ground.png',
  },
  'forbidden-greenhouse': {
    far: 'assets/stages/forbidden-greenhouse-far.png',
    mid: 'assets/stages/forbidden-greenhouse-mid.png',
    ground: 'assets/stages/forbidden-greenhouse-ground.png',
  },
  'storm-index-harbor': {
    far: 'assets/stages/storm-index-harbor-far.png',
    mid: 'assets/stages/storm-index-harbor-mid.png',
    ground: 'assets/stages/storm-index-harbor-ground.png',
  },
  'living-type-core': {
    far: 'assets/stages/living-type-core-far.png',
    mid: 'assets/stages/living-type-core-mid.png',
    ground: 'assets/stages/living-type-core-ground.png',
  },
};
let advLevelCounter = 0;
const ADVENTURE_LEVELS = ADVENTURE_CHAPTERS.flatMap((chapter, chapterIdx) =>
  chapter.levels.map((level, levelIdx) => ({
    ...level,
    chapterId: chapter.id,
    chapterTitle: chapter.title,
    stageTheme: chapter.stageTheme || chapter.id,
    chapterIdx,
    levelIdx,
    globalIdx: advLevelCounter++,
    mapLabel: (chapterIdx + 1) + '-' + (levelIdx + 1),
  }))
);
const CHAPTER_TITLES = ADVENTURE_CHAPTERS.map(chapter => chapter.title);
const MONSTER_TEMPLATES = ADVENTURE_CHAPTERS.map(chapter => chapter.levels);

const ADV_ITEM_DEFS = {
  heal: {
    icon: 'HP',
    name: '蜂蜜茶',
    short: '回復 25 HP',
    desc: '回復 25 HP，最多到上限。',
    max: 9,
  },
  cleanse: {
    icon: 'CLR',
    name: '橡皮擦',
    short: '清除負面磚',
    desc: '清除全盤鎖定與詛咒狀態。',
    max: 9,
  },
  strike: {
    icon: 'DMG',
    name: '墨水彈',
    short: '造成 22 傷害',
    desc: '對目前怪物造成 22 點傷害。',
    damage: 22,
    max: 9,
  },
};
const ADV_ITEM_ORDER = ['heal', 'cleanse', 'strike'];
